version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

build_script:
  - yarn build

artifacts:
  - path: dist
    name: build
